"""
Prompt templates and few-shot examples for PersonaReflect agents
"""

from .personas import (
    COGNITIVE_BEHAVIORAL_PROMPTS,
    EMPATHETIC_FRIEND_PROMPTS,
    RATIONAL_ANALYST_PROMPTS,
    MINDFULNESS_MENTOR_PROMPTS,
    ACTION_PLAN_PROMPTS,
    CONTEXT_PROMPTS
)

__all__ = [
    "COGNITIVE_BEHAVIORAL_PROMPTS",
    "EMPATHETIC_FRIEND_PROMPTS",
    "RATIONAL_ANALYST_PROMPTS",
    "MINDFULNESS_MENTOR_PROMPTS",
    "ACTION_PLAN_PROMPTS",
    "CONTEXT_PROMPTS"
]